export const ha_noi = [
	{
		id: 101,
		title: "Ba Đình",
		name: "Ba Đình - Hà Nội",
		alias: "ba-dinh-ha-noi",
	},
	{
		id: 102,
		title: "Hoàn Kiếm",
		name: "Hoàn Kiếm - Hà Nội",
		alias: "hoan-kiem-ha-noi",
	},
	{
		id: 103,
		title: "Hai Bà Trưng",
		name: "Hai Bà Trưng - Hà Nội",
		alias: "hai-ba-trung-ha-noi",
	},
	{
		id: 104,
		title: "Đống Đa",
		name: "Đống Đa - Hà Nội",
		alias: "dong-da-ha-noi",
	},
	{
		id: 105,
		title: "Tây Hồ",
		name: "Tây Hồ - Hà Nội",
		alias: "tay-ho-ha-noi",
	},
	{
		id: 106,
		title: "Cầu Giấy",
		name: "Cầu Giấy - Hà Nội",
		alias: "cau-giay-ha-noi",
	},
	{
		id: 107,
		title: "Thanh Xuân",
		name: "Thanh Xuân - Hà Nội",
		alias: "thanh-xuan-ha-noi",
	},
	{
		id: 108,
		title: "Hoàng Mai",
		name: "Hoàng Mai - Hà Nội",
		alias: "hoang-mai-ha-noi",
	},
	{
		id: 109,
		title: "Long Biên",
		name: "Long Biên - Hà Nội",
		alias: "long-bien-ha-noi",
	},
	{
		id: 110,
		title: "Từ Liêm",
		name: "Từ Liêm - Hà Nội",
		alias: "tu-liem-ha-noi",
	},
	{
		id: 111,
		title: "Thanh Trì",
		name: "Thanh Trì - Hà Nội",
		alias: "thanh-tri-ha-noi",
	},
	{
		id: 112,
		title: "Gia Lâm",
		name: "Gia Lâm - Hà Nội",
		alias: "gia-lam-ha-noi",
	},
	{
		id: 113,
		title: "Đông Anh",
		name: "Đông Anh - Hà Nội",
		alias: "dong-anh-ha-noi",
	},
	{
		id: 114,
		title: "Sóc Sơn",
		name: "Sóc Sơn - Hà Nội",
		alias: "soc-son-ha-noi",
	},
	{
		id: 115,
		title: "Hà Đông",
		name: "Hà Đông - Hà Nội",
		alias: "ha-dong-ha-noi",
	},
	{
		id: 116,
		title: "Sơn Tây",
		name: "Sơn Tây - Hà Nội",
		alias: "son-tay-ha-noi",
	},
	{
		id: 117,
		title: "Ba Vì",
		name: "Ba Vì - Hà Nội",
		alias: "ba-vi-ha-noi",
	},
	{
		id: 118,
		title: "Phúc Thọ",
		name: "Phúc Thọ - Hà Nội",
		alias: "phuc-tho-ha-noi",
	},
	{
		id: 119,
		title: "Thạch Thất",
		name: "Thạch Thất - Hà Nội",
		alias: "thach-that-ha-noi",
	},
	{
		id: 120,
		title: "Quốc Oai",
		name: "Quốc Oai - Hà Nội",
		alias: "quoc-oai-ha-noi",
	},
	{
		id: 121,
		title: "Chương Mỹ",
		name: "Chương Mỹ - Hà Nội",
		alias: "chuong-my-ha-noi",
	},
	{
		id: 122,
		title: "Đan Phượng",
		name: "Đan Phượng - Hà Nội",
		alias: "dan-phuong-ha-noi",
	},
	{
		id: 123,
		title: "Hoài Đức",
		name: "Hoài Đức - Hà Nội",
		alias: "hoai-duc-ha-noi",
	},
	{
		id: 124,
		title: "Thanh Oai",
		name: "Thanh Oai - Hà Nội",
		alias: "thanh-hoai-ha-noi",
	},
	{
		id: 125,
		title: "Mỹ Đức",
		name: "Mỹ Đức - Hà Nội",
		alias: "my-duc-ha-noi",
	},
	{
		id: 126,
		title: "Ứng Hoà",
		name: "Ứng Hoà - Hà Nội",
		alias: "ung-hoa-ha-noi",
	},
	{
		id: 127,
		title: "Thường Tín",
		name: "Thường Tín - Hà Nội",
		alias: "thuong-tin-ha-noi",
	},
	{
		id: 128,
		title: "Phú Xuyên",
		name: "Phú Xuyên - Hà Nội",
		alias: "phu-xuyen-ha-noi",
	},
	{
		id: 129,
		title: "Mê Linh",
		name: "Mê Linh - Hà Nội",
		alias: "me-linh-ha-noi",
	},
	{
		id: 130,
		title: "Bắc Từ Liêm",
		name: "Bắc Từ Liêm - Hà Nội",
		alias: "bac-tu-;liem-ha-noi",
	},
	{
		id: 131,
		title: "Nam Từ Liêm",
		name: "Nam Từ Liêm - Hà Nội",
		alias: "nam-tư-liêm-ha-noi",
	},
];
export const ho_chi_minh = [
	{
		id: 201,
		title: "Quận 1",
		name: "Quận 1 - TP HCM",
		alias: "quan-1-tp-hcm",
	},
	{
		id: 202,
		title: "Quận 2",
		name: "Quận 2 - TP HCM",
		alias: "quan-2-tp-hcm",
	},
	{
		id: 203,
		title: "Quận 3",
		name: "Quận 3 - TP HCM",
		alias: "quan-3-tp-hcm",
	},
	{
		id: 204,
		title: "Quận 4",
		name: "Quận 4 - TP HCM",
		alias: "quan-4-tp-hcm",
	},
	{
		id: 205,
		title: "Quận 5",
		name: "Quận 5 - TP HCM",
		alias: "quan-5-tp-hcm",
	},
	{
		id: 206,
		title: "Quận 6",
		name: "Quận 6 - TP HCM",
		alias: "quan-6-tp-hcm",
	},
	{
		id: 207,
		title: "Quận 7",
		name: "Quận 7 - TP HCM",
		alias: "quan-7-tp-hcm",
	},
	{
		id: 208,
		title: "Quận 8",
		name: "Quận 8 - TP HCM",
		alias: "quan-8-tp-hcm",
	},
	{
		id: 209,
		title: "Quận 9",
		name: "Quận 9 - TP HCM",
		alias: "quan-9-tp-hcm",
	},
	{
		id: 210,
		title: "Quận 10",
		name: "Quận 10 - TP HCM",
		alias: "quan-10-tp-hcm",
	},
	{
		id: 211,
		title: "Quận 11",
		name: "Quận 11 - TP HCM",
		alias: "quan-11-tp-hcm",
	},
	{
		id: 212,
		title: "Quận 12",
		name: "Quận 12 - TP HCM",
		alias: "quan-12-tp-hcm",
	},
	{
		id: 213,
		title: "Thủ Đức",
		name: "Thủ Đức - TP HCM",
		alias: "thu-duc-tp-hcm",
	},
	{
		id: 214,
		title: "Gò Vấp",
		name: "Gò Vấp - TP HCM",
		alias: "go-vap-tp-hcm",
	},
	{
		id: 215,
		title: "Bình Thạnh",
		name: "Bình Thạnh - TP HCM",
		alias: "binh-thach-tp-hcm",
	},
	{
		id: 216,
		title: "Tân Bình",
		name: "Tân Bình - TP HCM",
		alias: "tan-binh-tp-hcm",
	},
	{
		id: 217,
		title: "Tân Phú",
		name: "Tân Phú - TP HCM",
		alias: "tan-phu-tp-hcm",
	},
	{
		id: 218,
		title: "Phú Nhuận",
		name: "Phú Nhuận - TP HCM",
		alias: "phu-nhuan-tp-hcm",
	},
	{
		id: 219,
		title: "Bình Tân",
		name: "Bình Tân - TP HCM",
		alias: "binh-tan-tp-hcm",
	},
	{
		id: 220,
		title: "Củ Chi",
		name: "Củ Chi - TP HCM",
		alias: "cu-chi-tp-hcm",
	},
	{
		id: 221,
		title: "Hóc Môn",
		name: "Hóc Môn - TP HCM",
		alias: "hoc-mon-tp-hcm",
	},
	{
		id: 222,
		title: "Bình Chánh",
		name: "Bình Chánh - TP HCM",
		alias: "binh-chanh-tp-hcm",
	},
	{
		id: 223,
		title: "Nhà Bè",
		name: "Nhà Bè - TP HCM",
		alias: "nha-be-tp-hcm",
	},
	{
		id: 224,
		title: "Cần Giờ",
		name: "Cần Giờ - TP HCM",
		alias: "can-gio-tp-hcm",
	},
];
export const binh_duong = [
	{
		id: 301,
		title: "Dầu Tiếng",
		name: "Dầu Tiếng - Bình Dương",
		alias: "dau-tieng-binh-duong",
	},
	{
		id: 302,
		title: "Phú Giáo",
		name: "Phú Giáo - Bình Dương",
		alias: "phu-giao-binh-duong",
	},
	{
		id: 303,
		title: "Dĩ An",
		name: "Dĩ An - Bình Dương",
		alias: "di-an-binh-duong",
	},
	{
		id: 304,
		title: "Thuận An",
		name: "Thuận An - Bình Dương",
		alias: "thuan-an-binh-duong",
	},
	{
		id: 305,
		title: "Tân Uyên",
		name: "Tân Uyên - Bình Dương",
		alias: "tan-uyen-binh-duong",
	},
	{
		id: 306,
		title: "Bến Cát",
		name: "Bến Cát - Bình Dương",
		alias: "ben-cat-binh-duong",
	},
	{
		id: 307,
		title: "Thủ Dầu Một",
		name: "Thủ Dầu Một - Bình Dương",
		alias: "thu-dau-1-binh-duong",
	},
	{
		id: 6810,
		title: "Bắc Tân Uyên",
		name: "Bắc Tân Uyên - Bình Dương",
		alias: "bac-tan-uyen-binh-duong",
	},
	{
		id: 6811,
		title: "Bàu Bàng",
		name: "Bàu Bàng - Bình Dương",
		alias: "bau-bang-binh-duong",
	},
];
export const bac_ninh = [
	{
		id: 401,
		title: "Lương Tài",
		name: "Lương Tài - Bắc Ninh",
		alias: "luong-tai-bac-ninh",
	},
	{
		id: 402,
		title: "Gia Bình",
		name: "Gia Bình - Bắc Ninh",
		alias: "gia-binh-bac-ninh",
	},
	{
		id: 403,
		title: "Thuận Thành",
		name: "Thuận Thành - Bắc Ninh",
		alias: "thuan-thanh-bac-ninh",
	},
	{
		id: 404,
		title: "Từ Sơn",
		name: "Từ Sơn - Bắc Ninh",
		alias: "tu-son-bac-ninh",
	},
	{
		id: 405,
		title: "Tiên Du",
		name: "Tiên Du - Bắc Ninh",
		alias: "tien-du-bac-ninh",
	},
	{
		id: 406,
		title: "Quế Võ",
		name: "Quế Võ - Bắc Ninh",
		alias: "que-vo-bac-ninh",
	},
	{
		id: 407,
		title: "Yên Phong",
		name: "Yên Phong - Bắc Ninh",
		alias: "yen-phong-bac-ninh",
	},
	{
		id: 408,
		title: "TP Bắc Ninh",
		name: "TP Bắc Ninh",
		alias: "tp-bac-ninh",
	},
];
export const dong_nai = [
	{
		id: 501,
		title: "Cẩm Mỹ",
		name: "Cẩm Mỹ - Đồng Nai",
		alias: "cam-my-dong-nai",
	},
	{
		id: 502,
		title: "Trảng Bom",
		name: "Trảng Bom - Đồng Nai",
		alias: "trang-bom-dong-nai",
	},
	{
		id: 503,
		title: "Nhơn Trạch",
		name: "Nhơn Trạch - Đồng Nai",
		alias: "nhon-trach-dong-nai",
	},
	{
		id: 504,
		title: "Long Thành",
		name: "Long Thành - Đồng Nai",
		alias: "long-thanh-dong-nai",
	},
	{
		id: 505,
		title: "Xuân Lộc",
		name: "Xuân Lộc - Đồng Nai",
		alias: "xuan-loc-dong-nai",
	},
	{
		id: 506,
		title: "Long Khánh",
		name: "Long Khánh - Đồng Nai",
		alias: "long-khanh-dong-nai",
	},
	{
		id: 507,
		title: "Thống Nhất",
		name: "Thống Nhất - Đồng Nai",
		alias: "thong-nhat-dong-nai",
	},
	{
		id: 508,
		title: "Định Quán",
		name: "Định Quán - Đồng Nai",
		alias: "dinh-quan-dong-nai",
	},
	{
		id: 509,
		title: "Tân Phú",
		name: "Tân Phú - Đồng Nai",
		alias: "tan-phu-dong-nai",
	},
	{
		id: 510,
		title: "Vĩnh Cửu",
		name: "Vĩnh Cửu - Đồng Nai",
		alias: "vinh-cuu-dong-nai",
	},
	{
		id: 511,
		title: "Biên Hoà",
		name: "Biên Hoà - Đồng Nai",
		alias: "bien-hoa-dong-nai",
	},
];
