export const provinces = [
	{
		id: 1,
		name: "Hà Nội",
		alias: "ha_noi",
		districts: [
			{
				id: 101,
				title: "Ba Đình",
				name: "Ba Đình - Hà Nội",
				alias: "ba-dinh-ha-noi",
			},
			{
				id: 102,
				title: "Hoàn Kiếm",
				name: "Hoàn Kiếm - Hà Nội",
				alias: "hoan-kiem-ha-noi",
			},
			{
				id: 103,
				title: "Hai Bà Trưng",
				name: "Hai Bà Trưng - Hà Nội",
				alias: "hai-ba-trung-ha-noi",
			},
			{
				id: 104,
				title: "Đống Đa",
				name: "Đống Đa - Hà Nội",
				alias: "dong-da-ha-noi",
			},
			{
				id: 105,
				title: "Tây Hồ",
				name: "Tây Hồ - Hà Nội",
				alias: "tay-ho-ha-noi",
			},
			{
				id: 106,
				title: "Cầu Giấy",
				name: "Cầu Giấy - Hà Nội",
				alias: "cau-giay-ha-noi",
			},
			{
				id: 107,
				title: "Thanh Xuân",
				name: "Thanh Xuân - Hà Nội",
				alias: "thanh-xuan-ha-noi",
			},
			{
				id: 108,
				title: "Hoàng Mai",
				name: "Hoàng Mai - Hà Nội",
				alias: "hoang-mai-ha-noi",
			},
			{
				id: 109,
				title: "Long Biên",
				name: "Long Biên - Hà Nội",
				alias: "long-bien-ha-noi",
			},
			{
				id: 110,
				title: "Từ Liêm",
				name: "Từ Liêm - Hà Nội",
				alias: "tu-liem-ha-noi",
			},
			{
				id: 111,
				title: "Thanh Trì",
				name: "Thanh Trì - Hà Nội",
				alias: "thanh-tri-ha-noi",
			},
			{
				id: 112,
				title: "Gia Lâm",
				name: "Gia Lâm - Hà Nội",
				alias: "gia-lam-ha-noi",
			},
			{
				id: 113,
				title: "Đông Anh",
				name: "Đông Anh - Hà Nội",
				alias: "dong-anh-ha-noi",
			},
			{
				id: 114,
				title: "Sóc Sơn",
				name: "Sóc Sơn - Hà Nội",
				alias: "soc-son-ha-noi",
			},
			{
				id: 115,
				title: "Hà Đông",
				name: "Hà Đông - Hà Nội",
				alias: "ha-dong-ha-noi",
			},
			{
				id: 116,
				title: "Sơn Tây",
				name: "Sơn Tây - Hà Nội",
				alias: "son-tay-ha-noi",
			},
			{
				id: 117,
				title: "Ba Vì",
				name: "Ba Vì - Hà Nội",
				alias: "ba-vi-ha-noi",
			},
			{
				id: 118,
				title: "Phúc Thọ",
				name: "Phúc Thọ - Hà Nội",
				alias: "phuc-tho-ha-noi",
			},
			{
				id: 119,
				title: "Thạch Thất",
				name: "Thạch Thất - Hà Nội",
				alias: "thach-that-ha-noi",
			},
			{
				id: 120,
				title: "Quốc Oai",
				name: "Quốc Oai - Hà Nội",
				alias: "quoc-oai-ha-noi",
			},
			{
				id: 121,
				title: "Chương Mỹ",
				name: "Chương Mỹ - Hà Nội",
				alias: "chuong-my-ha-noi",
			},
			{
				id: 122,
				title: "Đan Phượng",
				name: "Đan Phượng - Hà Nội",
				alias: "dan-phuong-ha-noi",
			},
			{
				id: 123,
				title: "Hoài Đức",
				name: "Hoài Đức - Hà Nội",
				alias: "hoai-duc-ha-noi",
			},
			{
				id: 124,
				title: "Thanh Oai",
				name: "Thanh Oai - Hà Nội",
				alias: "thanh-hoai-ha-noi",
			},
			{
				id: 125,
				title: "Mỹ Đức",
				name: "Mỹ Đức - Hà Nội",
				alias: "my-duc-ha-noi",
			},
			{
				id: 126,
				title: "Ứng Hoà",
				name: "Ứng Hoà - Hà Nội",
				alias: "ung-hoa-ha-noi",
			},
			{
				id: 127,
				title: "Thường Tín",
				name: "Thường Tín - Hà Nội",
				alias: "thuong-tin-ha-noi",
			},
			{
				id: 128,
				title: "Phú Xuyên",
				name: "Phú Xuyên - Hà Nội",
				alias: "phu-xuyen-ha-noi",
			},
			{
				id: 129,
				title: "Mê Linh",
				name: "Mê Linh - Hà Nội",
				alias: "me-linh-ha-noi",
			},
			{
				id: 130,
				title: "Bắc Từ Liêm",
				name: "Bắc Từ Liêm - Hà Nội",
				alias: "bac-tu-;liem-ha-noi",
			},
			{
				id: 131,
				title: "Nam Từ Liêm",
				name: "Nam Từ Liêm - Hà Nội",
				alias: "nam-tư-liêm-ha-noi",
			},
		],
	},
	{
		id: 2,
		name: "Hồ Chí Minh",
		alias: "ho_chi_minh",
		districts: [
			{
				id: 201,
				title: "Quận 1",
				name: "Quận 1 - TP HCM",
				alias: "quan-1-tp-hcm",
			},
			{
				id: 202,
				title: "Quận 2",
				name: "Quận 2 - TP HCM",
				alias: "quan-2-tp-hcm",
			},
			{
				id: 203,
				title: "Quận 3",
				name: "Quận 3 - TP HCM",
				alias: "quan-3-tp-hcm",
			},
			{
				id: 204,
				title: "Quận 4",
				name: "Quận 4 - TP HCM",
				alias: "quan-4-tp-hcm",
			},
			{
				id: 205,
				title: "Quận 5",
				name: "Quận 5 - TP HCM",
				alias: "quan-5-tp-hcm",
			},
			{
				id: 206,
				title: "Quận 6",
				name: "Quận 6 - TP HCM",
				alias: "quan-6-tp-hcm",
			},
			{
				id: 207,
				title: "Quận 7",
				name: "Quận 7 - TP HCM",
				alias: "quan-7-tp-hcm",
			},
			{
				id: 208,
				title: "Quận 8",
				name: "Quận 8 - TP HCM",
				alias: "quan-8-tp-hcm",
			},
			{
				id: 209,
				title: "Quận 9",
				name: "Quận 9 - TP HCM",
				alias: "quan-9-tp-hcm",
			},
			{
				id: 210,
				title: "Quận 10",
				name: "Quận 10 - TP HCM",
				alias: "quan-10-tp-hcm",
			},
			{
				id: 211,
				title: "Quận 11",
				name: "Quận 11 - TP HCM",
				alias: "quan-11-tp-hcm",
			},
			{
				id: 212,
				title: "Quận 12",
				name: "Quận 12 - TP HCM",
				alias: "quan-12-tp-hcm",
			},
			{
				id: 213,
				title: "Thủ Đức",
				name: "Thủ Đức - TP HCM",
				alias: "thu-duc-tp-hcm",
			},
			{
				id: 214,
				title: "Gò Vấp",
				name: "Gò Vấp - TP HCM",
				alias: "go-vap-tp-hcm",
			},
			{
				id: 215,
				title: "Bình Thạnh",
				name: "Bình Thạnh - TP HCM",
				alias: "binh-thach-tp-hcm",
			},
			{
				id: 216,
				title: "Tân Bình",
				name: "Tân Bình - TP HCM",
				alias: "tan-binh-tp-hcm",
			},
			{
				id: 217,
				title: "Tân Phú",
				name: "Tân Phú - TP HCM",
				alias: "tan-phu-tp-hcm",
			},
			{
				id: 218,
				title: "Phú Nhuận",
				name: "Phú Nhuận - TP HCM",
				alias: "phu-nhuan-tp-hcm",
			},
			{
				id: 219,
				title: "Bình Tân",
				name: "Bình Tân - TP HCM",
				alias: "binh-tan-tp-hcm",
			},
			{
				id: 220,
				title: "Củ Chi",
				name: "Củ Chi - TP HCM",
				alias: "cu-chi-tp-hcm",
			},
			{
				id: 221,
				title: "Hóc Môn",
				name: "Hóc Môn - TP HCM",
				alias: "hoc-mon-tp-hcm",
			},
			{
				id: 222,
				title: "Bình Chánh",
				name: "Bình Chánh - TP HCM",
				alias: "binh-chanh-tp-hcm",
			},
			{
				id: 223,
				title: "Nhà Bè",
				name: "Nhà Bè - TP HCM",
				alias: "nha-be-tp-hcm",
			},
			{
				id: 224,
				title: "Cần Giờ",
				name: "Cần Giờ - TP HCM",
				alias: "can-gio-tp-hcm",
			},
		],
	},
	{
		id: 3,
		name: "Bình Dương",
		alias: "binh_duong",
		districts: [
			{
				id: 301,
				title: "Dầu Tiếng",
				name: "Dầu Tiếng - Bình Dương",
				alias: "dau-tieng-binh-duong",
			},
			{
				id: 302,
				title: "Phú Giáo",
				name: "Phú Giáo - Bình Dương",
				alias: "phu-giao-binh-duong",
			},
			{
				id: 303,
				title: "Dĩ An",
				name: "Dĩ An - Bình Dương",
				alias: "di-an-binh-duong",
			},
			{
				id: 304,
				title: "Thuận An",
				name: "Thuận An - Bình Dương",
				alias: "thuan-an-binh-duong",
			},
			{
				id: 305,
				title: "Tân Uyên",
				name: "Tân Uyên - Bình Dương",
				alias: "tan-uyen-binh-duong",
			},
			{
				id: 306,
				title: "Bến Cát",
				name: "Bến Cát - Bình Dương",
				alias: "ben-cat-binh-duong",
			},
			{
				id: 307,
				title: "Thủ Dầu Một",
				name: "Thủ Dầu Một - Bình Dương",
				alias: "thu-dau-1-binh-duong",
			},
			{
				id: 6810,
				title: "Bắc Tân Uyên",
				name: "Bắc Tân Uyên - Bình Dương",
				alias: "bac-tan-uyen-binh-duong",
			},
			{
				id: 6811,
				title: "Bàu Bàng",
				name: "Bàu Bàng - Bình Dương",
				alias: "bau-bang-binh-duong",
			},
		],
	},
	{
		id: 4,
		name: "Bắc Ninh",
		alias: "bac_ninh",
		districts: [
			{
				id: 401,
				title: "Lương Tài",
				name: "Lương Tài - Bắc Ninh",
				alias: "luong-tai-bac-ninh",
			},
			{
				id: 402,
				title: "Gia Bình",
				name: "Gia Bình - Bắc Ninh",
				alias: "gia-binh-bac-ninh",
			},
			{
				id: 403,
				title: "Thuận Thành",
				name: "Thuận Thành - Bắc Ninh",
				alias: "thuan-thanh-bac-ninh",
			},
			{
				id: 404,
				title: "Từ Sơn",
				name: "Từ Sơn - Bắc Ninh",
				alias: "tu-son-bac-ninh",
			},
			{
				id: 405,
				title: "Tiên Du",
				name: "Tiên Du - Bắc Ninh",
				alias: "tien-du-bac-ninh",
			},
			{
				id: 406,
				title: "Quế Võ",
				name: "Quế Võ - Bắc Ninh",
				alias: "que-vo-bac-ninh",
			},
			{
				id: 407,
				title: "Yên Phong",
				name: "Yên Phong - Bắc Ninh",
				alias: "yen-phong-bac-ninh",
			},
			{
				id: 408,
				title: "TP Bắc Ninh",
				name: "TP Bắc Ninh",
				alias: "tp-bac-ninh",
			},
		],
	},
	{
		id: 5,
		name: "Đồng Nai",
		alias: "dong_nai",
		districts: [
			{
				id: 501,
				title: "Cẩm Mỹ",
				name: "Cẩm Mỹ - Đồng Nai",
				alias: "cam-my-dong-nai",
			},
			{
				id: 502,
				title: "Trảng Bom",
				name: "Trảng Bom - Đồng Nai",
				alias: "trang-bom-dong-nai",
			},
			{
				id: 503,
				title: "Nhơn Trạch",
				name: "Nhơn Trạch - Đồng Nai",
				alias: "nhon-trach-dong-nai",
			},
			{
				id: 504,
				title: "Long Thành",
				name: "Long Thành - Đồng Nai",
				alias: "long-thanh-dong-nai",
			},
			{
				id: 505,
				title: "Xuân Lộc",
				name: "Xuân Lộc - Đồng Nai",
				alias: "xuan-loc-dong-nai",
			},
			{
				id: 506,
				title: "Long Khánh",
				name: "Long Khánh - Đồng Nai",
				alias: "long-khanh-dong-nai",
			},
			{
				id: 507,
				title: "Thống Nhất",
				name: "Thống Nhất - Đồng Nai",
				alias: "thong-nhat-dong-nai",
			},
			{
				id: 508,
				title: "Định Quán",
				name: "Định Quán - Đồng Nai",
				alias: "dinh-quan-dong-nai",
			},
			{
				id: 509,
				title: "Tân Phú",
				name: "Tân Phú - Đồng Nai",
				alias: "tan-phu-dong-nai",
			},
			{
				id: 510,
				title: "Vĩnh Cửu",
				name: "Vĩnh Cửu - Đồng Nai",
				alias: "vinh-cuu-dong-nai",
			},
			{
				id: 511,
				title: "Biên Hoà",
				name: "Biên Hoà - Đồng Nai",
				alias: "bien-hoa-dong-nai",
			},
		],
	},
	{
		id: 6,
		name: "Hưng Yên",
		alias: "hung_yen",
		districts: [],
	},
	{
		id: 7,
		name: "Hải Dương",
		alias: "hai_duong",
		districts: [],
	},
	{
		id: 8,
		name: "Đà Nẵng",
		alias: "da_nang",
		districts: [],
	},
	{
		id: 9,
		name: "Hải Phòng",
		alias: "hai_phong",
		districts: [],
	},
	{
		id: 10,
		name: "An Giang",
		alias: "an_giang",
		districts: [],
	},
	{
		id: 11,
		name: "Bà Rịa_Vũng Tàu",
		alias: "ba_ria_vung_tau",
		districts: [],
	},
	{
		id: 12,
		name: "Bắc Giang",
		alias: "bac_giang",
		districts: [],
	},
	{
		id: 13,
		name: "Bắc Kạn",
		alias: "bac_kan",
		districts: [],
	},
	{
		id: 14,
		name: "Bạc Liêu",
		alias: "bac_lieu",
		districts: [],
	},
	{
		id: 15,
		name: "Bến Tre",
		alias: "ben_tre",
		districts: [],
	},
	{
		id: 16,
		name: "Bình Định",
		alias: "binh_dinh",
		districts: [],
	},
	{
		id: 17,
		name: "Bình Phước",
		alias: "binh_phuoc",
		districts: [],
	},
	{
		id: 18,
		name: "Bình Thuận",
		alias: "binh_thuan",
		districts: [],
	},
	{
		id: 19,
		name: "Cà Mau",
		alias: "ca_mau",
		districts: [],
	},
	{
		id: 20,
		name: "Cần Thơ",
		alias: "can_tho",
		districts: [],
	},
	{
		id: 21,
		name: "Cao Bằng",
		alias: "cao_bang",
		districts: [],
	},
	{
		id: 22,
		name: "Cửu Long",
		alias: "cuu_long",
		districts: [],
	},
	{
		id: 23,
		name: "Đắk Lắk",
		alias: "dak_lak",
		districts: [],
	},
	{
		id: 24,
		name: "Đắc Nông",
		alias: "dac_nong",
		districts: [],
	},
	{
		id: 25,
		name: "Điện Biên",
		alias: "dien_bien",
		districts: [],
	},
	{
		id: 26,
		name: "Đồng Tháp",
		alias: "dong_thap",
		districts: [],
	},
	{
		id: 27,
		name: "Gia Lai",
		alias: "gia_lai",
		districts: [],
	},
	{
		id: 28,
		name: "Hà Giang",
		alias: "ha_giang",
		districts: [],
	},
	{
		id: 29,
		name: "Hà Nam",
		alias: "ha_nam",
		districts: [],
	},
	{
		id: 30,
		name: "Hà Tĩnh",
		alias: "ha_tinh",
		districts: [],
	},
	{
		id: 31,
		name: "Hậu Giang",
		alias: "hau_giang",
		districts: [],
	},
	{
		id: 32,
		name: "Hoà Bình",
		alias: "hoa_binh",
		districts: [],
	},
	{
		id: 33,
		name: "Khánh Hoà",
		alias: "khanh_hoa",
		districts: [],
	},
	{
		id: 34,
		name: "Kiên Giang",
		alias: "kien_giang",
		districts: [],
	},
	{
		id: 35,
		name: "Kon Tum",
		alias: "kon_tum",
		districts: [],
	},
	{
		id: 36,
		name: "Lai Châu",
		alias: "lai_chau",
		districts: [],
	},
	{
		id: 37,
		name: "Lâm Đồng",
		alias: "lam_dong",
		districts: [],
	},
	{
		id: 38,
		name: "Lạng Sơn",
		alias: "lang_son",
		districts: [],
	},
	{
		id: 39,
		name: "Lào Cai",
		alias: "lao_cai",
		districts: [],
	},
	{
		id: 40,
		name: "Long An",
		alias: "long_an",
		districts: [],
	},
	{
		id: 41,
		name: "Miền Bắc",
		alias: "mien_bac",
		districts: [],
	},
	{
		id: 42,
		name: "Miền Nam",
		alias: "mien_nam",
		districts: [],
	},
	{
		id: 43,
		name: "Miền Trung",
		alias: "mien_trung",
		districts: [],
	},
	{
		id: 44,
		name: "Nam Định",
		alias: "nam_dinh",
		districts: [],
	},
	{
		id: 45,
		name: "Nghệ An",
		alias: "nghe_an",
		districts: [],
	},
	{
		id: 46,
		name: "Ninh Bình",
		alias: "ninh_binh",
		districts: [],
	},
	{
		id: 47,
		name: "Ninh Thuận",
		alias: "ninh_thuan",
		districts: [],
	},
	{
		id: 48,
		name: "Phú Thọ",
		alias: "phu_tho",
		districts: [],
	},
	{
		id: 49,
		name: "Phú Yên",
		alias: "phu_yen",
		districts: [],
	},
	{
		id: 50,
		name: "Quảng Bình",
		alias: "quang_binh",
		districts: [],
	},
	{
		id: 51,
		name: "Quảng Nam",
		alias: "quang_nam",
		districts: [],
	},
	{
		id: 52,
		name: "Quảng Ngãi",
		alias: "quang_ngai",
		districts: [],
	},
	{
		id: 53,
		name: "Quảng Ninh",
		alias: "quang_ninh",
		districts: [],
	},
	{
		id: 54,
		name: "Quảng Trị",
		alias: "quang_tri",
		districts: [],
	},
	{
		id: 55,
		name: "Sóc Trăng",
		alias: "soc_trang",
		districts: [],
	},
	{
		id: 56,
		name: "Sơn La",
		alias: "son_la",
		districts: [],
	},
	{
		id: 57,
		name: "Tây Ninh",
		alias: "tay_ninh",
		districts: [],
	},
	{
		id: 58,
		name: "Thái Bình",
		alias: "thai_binh",
		districts: [],
	},
	{
		id: 59,
		name: "Thái Nguyên",
		alias: "thai_nguyen",
		districts: [],
	},
	{
		id: 60,
		name: "Thanh Hoá",
		alias: "thanh_hoa",
		districts: [],
	},
	{
		id: 61,
		name: "Thừa Thiên Huế",
		alias: "thua_thien_hue",
		districts: [],
	},
	{
		id: 62,
		name: "Tiền Giang",
		alias: "tien_giang",
		districts: [],
	},
	{
		id: 63,
		name: "Toàn Quốc",
		alias: "toan_quoc",
		districts: [],
	},
	{
		id: 64,
		name: "Trà Vinh",
		alias: "tra_vinh",
		districts: [],
	},
	{
		id: 65,
		name: "Tuyên Quang",
		alias: "tuyen_quang",
		districts: [],
	},
	{
		id: 66,
		name: "Vĩnh Long",
		alias: "vinh_long",
		districts: [],
	},
	{
		id: 67,
		name: "Vĩnh Phúc",
		alias: "vinh_phuc",
		districts: [],
	},
	{
		id: 68,
		name: "Yên Bái",
		alias: "yen_bai",
		districts: [],
	},
	{
		id: 100,
		name: "Nước Ngoài",
		alias: "nuoc_ngoai",
		districts: [],
	},
];
